services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: booking-app
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: booking
    image: postgres:18
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: booking
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d booking"]
      interval: 5s
      timeout: 5s
      retries: 5