services:
  postgres:
    container_name: booking
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: booking
    ports:
      - "5432:5432"